name: dev

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile

      - name: Run format
        run: pnpm format
      - name: Run reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: format

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile

      - name: Update version info
        run: |
          for dir in ./packages/*; do
            if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
              preid="dev-${GITHUB_SHA:0:8}"

              tmp="$(mktemp)"
              cat "$dir/package.json" > "$tmp"
              jq ".version = \"\(.version)-$preid\"" \
                "$tmp" > "$dir/package.json"
              rm "$tmp"
            fi
          done

      - run: pnpm build
      - run: pnpm test

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "$NODE_AUTH_TOKEN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish packages
        run: pnpm publish --tag dev --recursive --access public --no-git-checks
